# Kibana 9.2.0 Kubernetes 部署配置
# 与 Elasticsearch 9.2.0 兼容

---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: kibana
  labels:
    name: kibana

---
# ConfigMap for Kibana configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: kibana
  labels:
    app: kibana
data:
  kibana.yml: |
    # Kibana 9.2.0 配置 - 连接 HTTP Elasticsearch（测试环境）
    server.host: "0.0.0.0"
    server.port: 5601
    
    # Elasticsearch HTTP 连接
    elasticsearch.hosts: ["http://elasticsearch-service.elasticsearch.svc.cluster.local:9200"]
    xpack.security.enabled: false
    
    # 基本设置
    server.name: "kibana"
    i18n.locale: "zh-CN"

---
# Kibana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:9.2.0
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=1800"
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-service.elasticsearch.svc.cluster.local:9200"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "5601"
        - name: SERVER_NAME
          value: "kibana"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        - name: I18N_LOCALE
          value: "zh-CN"
        volumeMounts:
        - name: kibana-data
          mountPath: /usr/share/kibana/data
        - name: kibana-logs
          mountPath: /usr/share/kibana/logs
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: kibana-data
        emptyDir: {}
      - name: kibana-logs
        emptyDir: {}
      restartPolicy: Always

---
# Kibana ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: kibana
  labels:
    app: kibana
spec:
  type: ClusterIP
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    name: http
  selector:
    app: kibana