apiVersion: v1
kind: Config
clusters:
- name: minikube
  cluster:
    server: https://192.168.1.102:6443
    insecure-skip-tls-verify: true
users:
- name: kubepi-admin
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlhnSDlnOGRRcHF4UlVTYml5WEdtcjFVWW1zcFpwcXJqOE9JSnZ2WjhSVWcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzk0ODI2MTYwLCJpYXQiOjE3NjMyOTAxNjAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZGU2YzIxYzUtNmVlMS00MTQ2LWI2ZTgtYjc3NTEwMmRmMmU2Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlcGkiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoia3ViZXBpLWFkbWluIiwidWlkIjoiMTFmNWQ4YTctZDYyOC00M2E5LWIzMGMtZTliZmNhYmQzNjViIn19LCJuYmYiOjE3NjMyOTAxNjAsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcGk6a3ViZXBpLWFkbWluIn0.wL90uJHN_xv7dku6NBduW9uybAf2_Z-1yNcoju4Qx2anTVr4khoMnPUhO-vUK8-VywHED-dE0YbJqOa7xUedQMTZfz06W5pKIlQuNu1pk4_EzCQUWTbFMYM6-mjUytl9TK5J27SGigw3Rdxcjw2WtJhTA0ycRwh_jTesDuI3qlmu6LWk-GHQY0bf-pyjWTXsmy8C0aTcQKEfcQB9ysA2T2-3E-G44r5bmFfsq2_9xc3ls8MYxvB7ihRUBFleXcmqfeIZFxx9kcLsBv3qmxlBn2WzQLOXU5gcVWFUtwhm-PhkN26DQM3_ZHp-SJBbC5TJk7-Jo5Z3J2jlK_tHjteLdw
contexts:
- name: kubepi-admin@minikube
  context:
    cluster: minikube
    user: kubepi-admin
current-context: kubepi-admin@minikube