apiVersion: v1
kind: Namespace
metadata:
  name: nacos
  labels:
    name: nacos

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
  namespace: nacos
data:
  application.properties: |
    server.servlet.contextPath=/nacos
    server.port=8848
    spring.datasource.platform=mysql
    db.num=1
    db.url.0=jdbc:mysql://mysql-service.mysql.svc.cluster.local:3306/nacos?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    db.user=root
    db.password=mysql123
    spring.sql.init.platform=mysql
    management.endpoints.web.exposure.include=*
    nacos.core.auth.enabled=false
    logging.level.root=INFO

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: nacos
  labels:
    app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v2.3.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8848
          name: http
          protocol: TCP
        env:
        - name: MODE
          value: "standalone"
        - name: SPRING_DATASOURCE_PLATFORM
          value: "mysql"
        - name: MYSQL_SERVICE_HOST
          value: "mysql-service.mysql.svc.cluster.local"
        - name: MYSQL_SERVICE_DB_NAME
          value: "nacos"
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_SERVICE_USER
          value: "root"
        - name: MYSQL_SERVICE_PASSWORD
          value: "mysql123"
        volumeMounts:
        - name: nacos-config
          mountPath: /home/nacos/conf/application.properties
          subPath: application.properties
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /nacos
            port: 8848
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /nacos
            port: 8848
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
      volumes:
      - name: nacos-config
        configMap:
          name: nacos-config

---
apiVersion: v1
kind: Service
metadata:
  name: nacos-service
  namespace: nacos
  labels:
    app: nacos
spec:
  type: ClusterIP
  selector:
    app: nacos
  ports:
  - name: http
    port: 8848
    targetPort: 8848
    protocol: TCP