# KubePi Kubernetes 部署配置
# 包含 Namespace, PVC, ConfigMap, Deployment, Service

---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: kubepi
  labels:
    name: kubepi

---
# PersistentVolumeClaim for data persistence
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubepi-data-pvc
  namespace: kubepi
  labels:
    app: kubepi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # 根据你的集群存储类调整

---
# ConfigMap for KubePi configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubepi-config
  namespace: kubepi
  labels:
    app: kubepi
data:
  # KubePi 配置参数
  server.properties: |
    # 服务器配置
    server.port=80
    # 数据库配置 (使用内置SQLite)
    datasource.driver-class-name=org.sqlite.JDBC
    datasource.url=jdbc:sqlite:/opt/kubepi/db/kubepi.db
    # 日志配置
    logging.level.root=INFO
    logging.level.com.fit2cloud=DEBUG

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepi
  namespace: kubepi
  labels:
    app: kubepi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubepi
  template:
    metadata:
      labels:
        app: kubepi
    spec:
      containers:
      - name: kubepi
        image: 1panel/kubepi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: KP_MODE
          value: "server"
        - name: KP_IP
          value: "0.0.0.0"
        - name: KP_PORT
          value: "80"
        volumeMounts:
        - name: kubepi-data
          mountPath: /opt/kubepi/db
        - name: kubepi-config
          mountPath: /opt/kubepi/conf
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: kubepi-data
        persistentVolumeClaim:
          claimName: kubepi-data-pvc
      - name: kubepi-config
        configMap:
          name: kubepi-config
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: kubepi-service
  namespace: kubepi
  labels:
    app: kubepi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: kubepi