# Elasticsearch 8 Kubernetes 部署配置
# 包含命名空间、配置映射、持久化存储、部署和服务

---
# 命名空间
apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch

---
# ConfigMap - Elasticsearch 配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    
    # 发现配置 - 单节点模式
    discovery.type: single-node
    
    # 安全配置 - 启用HTTPS/TLS (简化配置)
    xpack.security.enabled: true
    xpack.security.enrollment.enabled: true
    xpack.security.http.ssl.enabled: true
    xpack.security.transport.ssl.enabled: false
    
    # SSL/TLS 配置 - 使用自签名证书
    xpack.security.http.ssl.keystore.path: certs/http.p12
    xpack.security.http.ssl.keystore.password: ""
    
    # 内存配置
    bootstrap.memory_lock: false
    
    # 网络配置
    http.port: 9200
    transport.port: 9300
    
    # 日志配置
    logger.level: INFO

---
# PersistentVolumeClaim - 数据持久化
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
# Deployment - Elasticsearch 部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:9.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        env:
        - name: node.name
          value: "elasticsearch-0"
        - name: cluster.name
          value: "docker-cluster"
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: xpack.security.enabled
          value: "true"
        - name: xpack.security.enrollment.enabled
          value: "true"
        - name: ELASTIC_PASSWORD
          value: "elastic123"
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: elasticsearch-certs
          mountPath: /usr/share/elasticsearch/config/certs
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              curl -k -u elastic:elastic123 https://localhost:9200/_cluster/health || exit 1
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              curl -k -u elastic:elastic123 https://localhost:9200/_cluster/health || exit 1
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config
      - name: elasticsearch-certs
        emptyDir: {}
      initContainers:
      - name: setup-certs
        image: elasticsearch:9.2.0
        command: ['sh', '-c']
        args:
          - |
            if [ ! -f /usr/share/elasticsearch/config/certs/http.p12 ]; then
              echo "生成自签名SSL证书..."
              /usr/share/elasticsearch/bin/elasticsearch-certutil cert --silent --self-signed --out /usr/share/elasticsearch/config/certs/http.p12 --pass ""
              echo "证书生成完成"
            else
              echo "证书已存在，跳过生成"
            fi
        volumeMounts:
        - name: elasticsearch-certs
          mountPath: /usr/share/elasticsearch/config/certs
      - name: increase-vm-max-map
        image: busybox:1.35
        command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        securityContext:
          privileged: true

---
# Service - NodePort (外部访问)
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30920
    protocol: TCP
    name: http
  - port: 9300
    targetPort: 9300
    nodePort: 30930
    protocol: TCP
    name: transport
  selector:
    app: elasticsearch

---
# Service - NodePort (外部访问)
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30920
    protocol: TCP
    name: http
  - port: 9300
    targetPort: 9300
    nodePort: 30930
    protocol: TCP
    name: transport
  selector:
    app: elasticsearch